### ISSUE TITLE
Python 3 compatibility?

### ISSUE THREAD

**Issue by jleclanche** [google/grumpy#1]
Alright, I'll straight up ask: What's the status of Python 3 compatibility for this runtime? Never/Maybe someday/Working on it?

**Comment by trotterdylan** [comment]
We have a large Python 2.7 codebase so that's what we've been focused on. I definitely would like to support Python 3. It's just a bunch of work. Probably requires forking grumpy and building out all the v3 features.

Another path may be to support Python 3 features in the existing Grumpy runtime and transpiler at the risk of making things less maintainable.

**Comment by jacobmischka** [comment]
I think in the meantime it should be noted very explicitly that it's a python2 runtime. Both the repo and the associated blog post just mention "python" everywhere except in one sentence that mentions 2.7. It's 2017, "python" should really mean python3 by now.

Regardless, this looks really neat, great work everyone!

**Comment by trotterdylan** [comment]
That's fair, I'll update the README.

**Comment by jacobmischka** [comment]
Thanks! Sorry to be blunt 🐣

**Comment by marcintustin** [comment]
I honestly don't think python means python 3, and it's completely fair to only support the vast majority of python code in production. 

If nothing else "python 3" is still a moving target because - whatever its partisans like to say - the project operates as if it were a research language.

**Comment by ClaymorePT** [comment]
@marcintustin  

> Python3 is still a moving target?

 Have you seen this -> https://pythonclock.org/

**Comment by wimglenn** [comment]
It's 2017.  There is _Python_ and there is _The Language Formerly Known as Python_.

**Comment by jacobmischka** [comment]
Certainly it's fair to only support what they're using it for. I just asked that it be made clear.

**Comment by marcintustin** [comment]
@ClaymorePT Page me when that stops being extended or python 3 represents a stable target that most python code targets. I fundamentally don't care about the CPython maintenance schedule because it's clear the community as a whole is still investing in Python 2.7. Grumpy is one example of that.

**Comment by jleclanche** [comment]
This is honestly not the place to argue whether you prefer python 2 or 3, or whether to invest into python 2 or 3. I opened this issue to figure out how likely it is for grumpy to get 3 support because I personally am really, *really* interested in this project and would like to use it for Python 3 code.

**Comment by thalesmello** [comment]
@trotterdylan 

Are there any official Google projects that use Python 3, or folks over there plan on using Python 2 for the next 10 years?

Has Google ever considered migrating to Python 3?

Maybe tools like [2to3](https://docs.python.org/2/library/2to3.html) could ease up the process?

I'm not trying to play the troll here, those are sincere questions.

I would really like to see Python 3 support in grumpy, but I completely understand the desired goals of the project.

**Comment by ClaymorePT** [comment]
10 years have passed since the arrival of Python 3. It is already at version 3.6, one before the last release of Python 2.7.
If until now, they did not consider moving on to Python 3, then I don't think they ever will.
Besides, they also have Go and Clang.

**Comment by cclauss** [comment]
8.5 years but who is counting  ;-)  "Patience is a virtue but I don't have the time." -- Talking Heads

```python
from datetime import date
delta = date.today() -date(2008, 12, 3)
print(f'{delta.days / 365.25:.2f} years')  # f-strings require Python 3.6 or later
```

**Comment by ClaymorePT** [comment]
I stand corrected!

**Comment by Azareal** [comment]
https://opensource.googleblog.com/2017/01/grumpy-go-running-python.html

```Google runs millions of lines of Python code.```

Millions of lines of *working* Python code which they would have to thoroughly test, etc. before rolling out a Python 3 equivalent. I'm not really sure it makes sense from a business standpoint, especially since they've built their own system.

While Python 3 is obviously on my wishlist, I personally can't see it happening for the next five years or so. This project is a massive undertaking to begin with.

**Comment by ClaymorePT** [comment]
Like I said. If they haven't started to move to Python 3, they probably never will.
But that's not an excuse to not to use Python 3 with new projects or, not to update smaller projects to Python 3.
