### ISSUE TITLE
builtinMapFn makes unchecked call to toFunctionUnsafe

### ISSUE THREAD

**Issue by nairb774** [google/grumpy#115]
One of the [test cases](https://github.com/google/grumpy/blob/de6c1bc33b127cb95c0ecc8bdc5a8aaa88927000/runtime/builtin_types_test.go#L169) passes None to the map builtin which is run through [toFunctionUnsafe](https://github.com/google/grumpy/blob/de6c1bc33b127cb95c0ecc8bdc5a8aaa88927000/runtime/builtin_types.go#L202) without first checking that such a conversion is safe. I discovered the unsafe cast when rebasing #58 to head.

**Comment by trotterdylan** [comment]
Good find. Not sure how I overlooked that during review. Fixed in c8d72d9.

**Comment by S-YOU** [comment]
Thanks for the report and fixes, I actually didn't know Object can call it directly.
