### ISSUE TITLE
Can't access Go struct fields from Python

### ISSUE THREAD

**Issue by ns-cweber** [google/grumpy#12]
The following code fails with the error message: `AttributeError: '*Response' object has no attribute 'Body'`

```py
from __go__.os import Stdout as stdout
from __go__.net.http import DefaultClient as client

rsp, err = client.Get("http://www.google.com")
if err is not None:
    raise Exception(err.Error())

_, err = Copy(stdout, rsp.Body)
if err is not None:
    raise Exception(err.Error())
```

**Comment by trotterdylan** [comment]
Thanks for submitting this. I think this used to work but the native interface has been rewritten a couple times and I think this feature got lost in the shuffle at some point. Will take a look.
