### ISSUE TITLE
Using `continue` in `else` block of `for else`

### ISSUE THREAD

**Issue by S-YOU** [google/grumpy#123]
I am not sure `for else` is fully supported, but here is the one I noticed while fixing re bugs.

```
for i in range(2):
  print 'i', i
  for j in range(2):
    print 'i', i, "j", j
  else:
    print "continue", i, j
    continue
```

CPython
```
i 0
i 0 j 0
i 0 j 1
continue 0 1
i 1
i 1 j 0
i 1 j 1
continue 1 1
```

grumpy
```
i 0
i 0 j 0
i 0 j 1
continue 0 1
TypeError: int object is not an iterator
exit status 1
```

May be else's scope is bind to inner loop, not outer loop?

**Comment by trotterdylan** [comment]
Good find! It never occurred to me that a continue could appear in an else clause :\

It seems like the correct behavior is that continue applies to the outer loop because if you continue in a non-nested loop you get:

```
>>> for j in range(2):
...   print "j", j
... else:
...  print "continue", j
...  continue
...
  File "<stdin>", line 5
SyntaxError: 'continue' not properly in loop
```

**Comment by S-YOU** [comment]
I never used too but, that re module use it in awkward way, and outer loop is while True.
