### ISSUE TITLE
make precommit error

### ISSUE THREAD

**Issue by mmclkv** [google/grumpy#130]
Seems that I just can't get pylint successfully installed in build/bin when running make precommit.

Here's a part of the log:

`Running setup.py install for lazy-object-proxy`
    
    `warning: no directories found matching 'examples'`
    `warning: no files found matching '.isort.cfg'`
    `warning: no previously-included files matching '*.py[cod]' found anywhere in distribution`
    `warning: no previously-included files matching '__pycache__' found anywhere in distribution`
    `warning: no previously-included files matching '*.so' found anywhere in distribution`
    `warning: no previously-included files matching '*.dylib' found anywhere in distribution`
    `building 'lazy_object_proxy.cext' extension`
    `x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Isrc/lazy_object_proxy -I/usr/include/python2.7 -c src/lazy_object_proxy/cext.c -o build/temp.linux-x86_64-2.7/src/lazy_object_proxy/cext.o`
    `x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/lazy_object_proxy/cext.o -o build/lib.linux-x86_64-2.7/lazy_object_proxy/cext.so`
`Successfully installed pylint configparser backports.functools-lru-cache six isort mccabe astroid wrapt lazy-object-proxy`
`Cleaning up...`
`/bin/sh: 1: build/bin/pylint: not found`

**Comment by trotterdylan** [comment]
Thanks for reporting this! I've had lots of problems with pip and pylint. I'm thinking I need to bundle a fixed version of pylint in third_party instead of relying on system pip.

**Comment by mmclkv** [comment]
So if I want to do a pull request, what should I do?Just running "make test" instead?

**Comment by trotterdylan** [comment]
`make precommit` is the equivalent of `make cover gofmt golint pylint test` so if you want to skip pylint but do the rest you can do:

```
make cover gofmt golint test
```

**Comment by mmclkv** [comment]
Got it! Thanks!

**Comment by trotterdylan** [comment]
This *may* have been fixed in https://github.com/google/grumpy/pull/143

Let me know if it helps.

**Comment by mmclkv** [comment]
I think it works now. Thanks!

**Comment by trotterdylan** [comment]
Thanks for the confirmation. Closing for now. Reopen if it recurs.
