### ISSUE TITLE
Question: Is it possible to do the following workflow

### ISSUE THREAD

**Issue by deckarep** [google/grumpy#149]
1. Is it possible to reference existing structs in pre-existing (regular) Go code?
2. Import those exported fields and write Grumpy based Python code
3. Then, reference the resultant generated Grumpy Go code from real existing Go code?

My workflow is the following:  I'd like to write most of my application code in vanilla Go code, but write tedious and functional-style code in Grumpy using things like list comprehensions.  Then reference that code from the vanilla Go code.

If possible I'd like to see if I can leverage Grumpy for partial code generation when writing code that looks like the following:

```
[x for x in some_collection if x > 10] # sample list comprehension
```

**Comment by trotterdylan** [comment]
Thanks for asking! This use case is interesting to me. IIUC, I think all of this is possible now:

For 1. & 2: it is possible to use Go structs in Python code. See [native_test.py](https://github.com/google/grumpy/blob/master/testing/native_test.py#L31) for an example

For 3: This has been discussed in https://github.com/google/grumpy/issues/10. It is possible, but it's a little verbose. The interface for accessing Python objects from Go will hopefully get a little nicer as time goes on.

I'm going to close this for now. If you have specific feature requests relating to this, please feel free to open more issues.

**Comment by deckarep** [comment]
Thank you for the quick answer! Your answers give me a great starting point.
