### ISSUE TITLE
how can I transfer django file to go file

### ISSUE THREAD

**Issue by epth** [google/grumpy#173]
when I try to transfer django file to go file,it told me that I don't have the django library

**Comment by trotterdylan** [comment]
If you're asking whether django is supported by Grumpy, the answer is "not yet". Please reopen if this issue is about something else.

**Comment by cclauss** [comment]
The current http://pycoders.com weekly speculates that Django v2 is dropping support for Python 2 so it might be a long wait.

**Comment by alanjds** [comment]
As seen on the graph [here](https://www.djangoproject.com/download/#supported-versions), 1.11 LTS (April 2017) will be the last Python 2 version and will span support "Until at least April 2020"
