### ISSUE TITLE
silent assertion error

### ISSUE THREAD

**Issue by wuttem** [google/grumpy#18]
I tried running the following python code:
```
print("before assert")
assert False
print("after assert")
```
Output:
```
mths@MTHS-T450s:~/go/grumpy$ ./test
before assert
mths@MTHS-T450s:~/go/grumpy$ echo $?
0
```
Assert exited the program silently and the return code was 0.
If i changed the code to the following it works like i would expect it.
```
print("before assert")
try:
    assert False
except:
    raise AssertionError
print("after assert")
```
Output:
```
mths@MTHS-T450s:~/go/grumpy$ ./test
before assert
AssertionError
mths@MTHS-T450s:~/go/grumpy$ echo $?
1
```

Shouldn't this also happen in the first example? Am i missing something?

**Comment by wuttem** [comment]
I found this issue because I tried to run some of the stdlib tests.
One of the testcases (time_test.py) is:
```
import time

assert time.time() > 1000000000
assert time.time() < 3000000000
```
I tried running it with:
```
make run < lib/time_test.py
```
If i run this it would silently run/fail if there was an error.
Is there a better way to run such tests with this issue ?

**Comment by trotterdylan** [comment]
This should be fixed in https://github.com/google/grumpy/commit/802efc02babab947ca94f90147c660afbdb2da87
