### ISSUE TITLE
Support PYTHONPATH

### ISSUE THREAD

**Issue by alanjds** [google/grumpy#190]
Only internal folders are searched for pure-python modules for now. Support for PYTHONPATH at least is needed to support pip and 3rd-party packages, as asked by #5 and commented on https://groups.google.com/d/msg/grumpy-users/JJFFube8qkM/4VdycDi1FQAJ

**Comment by trotterdylan** [comment]
I think https://github.com/google/grumpy/issues/43 captures this discussion. I'm going to close this issue but could use your input on the other one. If you think it's a distinct issue, feel free to reopen.

**Comment by alanjds** [comment]
I guess it would be more manageable to have issues for specific features. This way, high-level needs/wishes could link to the feature-bugs and see if all of it are closed. Otherwise we could see a lot of "make project Foo work" issues with the same needs and no one knowing how near we are of fulfilling the needs.

**Comment by S-YOU** [comment]
Something like this? - https://github.com/google/grumpy/wiki/Missing-features

**Comment by alanjds** [comment]
YESSSS!

See the checklist here on [#43](https://github.com/google/grumpy/issues/43#issue-199038427) and another checklist on your link? This is a bad signal!
