### ISSUE TITLE
"make install" fails on Mac OS X

### ISSUE THREAD

**Issue by cclauss** [google/grumpy#210]
Mac OS X install command does not accept -D (capital D)

$ install
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...

**Comment by trotterdylan** [comment]
From man install: -D create all leading components of DEST except the last, then copy SOURCE to DEST

Looks like we could add an extra step to the recipe to just do `mkdir -p` on dirname of the target.

**Comment by cclauss** [comment]
Closed by https://github.com/google/grumpy/pull/213
