### ISSUE TITLE
Cannot build on macOS 10.12.2

### ISSUE THREAD

**Issue by miguelammatos** [google/grumpy#211]
$ git show --summary
commit e91485cb544304d67e4c240f8ac77aa72072248a

$ make clean

$ make
build/src/grumpy/builtin_types.go:780: z.Text undefined (type big.Int has no field or method Text)
build/src/grumpy/long.go:144: x.Text undefined (type *big.Int has no field or method Text)
build/src/grumpy/long.go:298: toLongUnsafe(o).value.Text undefined (type big.Int has no field or method Text)
build/src/grumpy/long.go:306: toLongUnsafe(o).value.Text undefined (type big.Int has no field or method Text)
build/src/grumpy/str.go:855: toLongUnsafe(o).Value().Text undefined (type *big.Int has no field or method Text)
make: *** [build/pkg/darwin_amd64/grumpy.a] Error 1

$ /usr/bin/env python -V
Python 2.7.3

**Comment by trotterdylan** [comment]
What version of go are you running: go version

**Comment by miguelammatos** [comment]
$go version
go version go1.5.1 darwin/amd64

**Comment by trotterdylan** [comment]
I think the minimum required version is either 1.6 or 1.7.

**Comment by miguelammatos** [comment]
Thanks, I'll update and recheck.

**Comment by miguelammatos** [comment]
It works with version 1.7.4.
It would be nice to have this in the requirements, I've submitted a PR that checks this on the Makefile similarly to what done for python.
