### ISSUE TITLE
Cannot find package "grumpy/lib/requests" 

### ISSUE THREAD

**Issue by zhangmaku** [google/grumpy#242]
Cannot find package "grumpy/lib/requests" in any of:
	/usr/local/go/src/grumpy/lib/requests (from $GOROOT)
	/src/grumpy-master/build/src/grumpy/lib/requests (from $GOPATH)
	/src/grumpy-master/build/pkg/linux_amd64/src/grumpy/lib/requests
	/usr/lib/go/pkg/linux_amd64/src/grumpy/lib/requests
	/usr/lib/go/pkg/linux_amd64_shared/src/grumpy/lib/requests

**Comment by trotterdylan** [comment]
When do you encounter this issue? What source is being compiled when this error is encountered?

**Comment by zhangmaku** [comment]
```
pip2 install requests`
echo 'import requests' > hello.py 
make
export GOPATH=$PWD/build
export PYTHONPATH=$PWD/build/lib/python2.7/site-packages
build/bin/grumpc hello.py > hello.go
go build -o hello hello.go
```
How to compile requests to PYTHONPATH?

**Comment by trotterdylan** [comment]
Python libraries on the PYTHONPATH are not yet supported by the build system. You need to pull the requests package into the grumpy src tree in the lib/ subdir for it to work with the existing build system. This is a known limitation and there's plenty of discussion in https://github.com/google/grumpy/issues/43
