### ISSUE TITLE
Local Imports

### ISSUE THREAD

**Issue by drgrib** [google/grumpy#246]
I'm unclear on how grumpy supports local imports. How should I implement the following scenario, where the following files are in the same directory?

**`hiStuff.py`**

```
def sayHi():
	print("Hello!")
```

**`importTest.py`**

```
import hiStuff

if __name__ == '__main__':
	hiStuff.sayHi()
```

Transcompiling `hiStuff.py` works but on the transcompile of `importTest.py`, I get:

```
grumpc importTest.py > importTest.go
go build -o importTest importTest.go
importTest.go:4:2: cannot find package "grumpy/lib/hiStuff" in any of:
	/usr/local/go/src/grumpy/lib/hiStuff (from $GOROOT)
	<grumpy location>/grumpy/build/src/grumpy/lib/hiStuff (from $GOPATH)
	<grumpy location>/grumpy/lib/hiStuff
make: *** [importTest] Error 1
```

Is the current directory not included in the import path or am I doing this wrong?

**Comment by trotterdylan** [comment]
It just follows the normal GOPATH rules. The trick is that imports are prefixed with "grumpy/lib" so you need to put your files in src/grumpy/lib. This is not ideal but I haven't had a chance to make the build system better yet. I think these limitations are captured by these other issues:

https://github.com/google/grumpy/issues/5
https://github.com/google/grumpy/issues/43

Feel free to chime in on those issues.

**Comment by drgrib** [comment]
@trotterdylan Okay, I'm trying this but I'm really unclear as to what types of source files need to be moved where. Do I need to compile a `hiStuff.a` and put it in the `$GOPATH` area? Do I need to move `hiStuff.py` to the `grumpy/lib` installation area and use `setuptools`? What's the standard way to do this?

**Comment by trotterdylan** [comment]
The easiest thing to do is drop your .py files into the lib/ dir in the grumpy source and then run make. That will build the .go and .a files and put them in the build/ subdir which is used as the GOPATH from the Makefile.

If you're more adventurous and have your own GOPATH dir, you can use grumpc directly to generate .go files, and then copy them into $GOPATH/src/grumpy/lib.

There is no standard way to do any of this yet since we're still focused on getting the standard library working. The bugs that I linked discuss some of the requirements and approaches we're considering for the long term.

**Comment by drgrib** [comment]
@trotterdylan I like the `$GOPATH/src/grumpy/lib` solution best. However, even after moving `hiStuff.go` there, when I try

```
grumpc importTest.py > importTest.go
go build -o importTest importTest.go
```
I get
```
importTest.go:4:2: cannot find package "grumpy/lib/hiStuff" in any of:
	/usr/local/go/src/grumpy/lib/hiStuff (from $GOROOT)
	<grumpy parent dir>/grumpy/build/src/grumpy/lib/hiStuff (from $GOPATH)
	<grumpy parent dir>/grumpy/lib/hiStuff
```

**Comment by drgrib** [comment]
@trotterdylan Alright, just shifted to the `$GRUMPYPATH/lib` solution. It just works. And the `make` ran faster than expected. I'll just do that.
