### ISSUE TITLE
cannot find package "grumpy/lib/math" 

### ISSUE THREAD

**Issue by kubaroth** [google/grumpy#26]
Trying to wrap my hand around the above error. Does his expect to provide grumpy math library implementation similarly to say, time.py?

**Comment by nairb774** [comment]
CPython has [the math module](https://hg.python.org/cpython/file/2.7/Modules/_math.c) implemented as a C extension. Looks like a Grumpy shim package (like time.py) is needed.

Give it a spin and see where you get?

**Comment by trotterdylan** [comment]
Right we do need a math shim but when is that error showing up? Are you importing math or adding a new module that imports math? Can you paste the command line and whole output?

**Comment by kubaroth** [comment]
Sure, python source first:
```
import math
print math.sqrt(4)
```

The output:
```
$ tools/grumpc hello.py > hello.go
$ go build -o hello hello.go
hello.go:4:2: cannot find package "grumpy/lib/math" in any of:
	/home/kuba/toolchains/go/src/grumpy/lib/math (from $GOROOT)
	/home/kuba/SRC/grumpy/build/src/grumpy/lib/math (from $GOPATH)

```

**Comment by kubaroth** [comment]
I gave it a go and turns out I had to only add a math.py into grumpy/lib
```
from __go__.math import Sqrt  # pylint: disable=g-multiple-import

def sqrt(val):
  return Sqrt(val)
```

**Comment by trotterdylan** [comment]
Thanks for the update. There is a PR in progress to address this: https://github.com/google/grumpy/pull/33

**Comment by kubaroth** [comment]
Great, thanks for the update. I think we can close this one then.

**Comment by lalaithion** [comment]
PR #33 has been merged, this issue should be closed.
