### ISSUE TITLE
open() does not support w+ and a+ modes

### ISSUE THREAD

**Issue by trotterdylan** [google/grumpy#268]
Per the [docs](https://docs.python.org/2/library/functions.html#open) this mode is legit.

For some reason I didn't support it in [file.go](https://github.com/google/grumpy/blob/master/runtime/file.go#L123).

```
$ echo 'open("foo.txt", "w+")' | make run
ValueError: invalid mode string: "w+"
```

**Comment by yashpatel5400** [comment]
Added these new features in #271

**Comment by yashpatel5400** [comment]
#271
