### ISSUE TITLE
Importing stdlib functions

### ISSUE THREAD

**Issue by yashpatel5400** [google/grumpy#273]
Is there a reason why only some of the files from https://github.com/python/cpython/tree/master/Lib have been copied to the thirdparty/stdlib folder? I was looking at the feature map from https://github.com/google/grumpy/wiki/Missing-features, which makes it seem like a lot of the features would be covered in duplicating most of the CPython Lib files.

**Comment by trotterdylan** [comment]
There are a couple reasons. One is that not all language features and builtins are implemented so some files don't work. The other is that many libraries depend on modules that are written as C extensions in CPython. Grumpy does not support C extensions, so those modules need to be rewritten from scratch or brought in from PyPy. That work is still ongoing.

That said, a lot of progress has been made over the last couple months, so there's good reason to believe many libraries can be integrated cleanly now.

I'm going to close this issue. Please open issues for specific features or libraries that need to be implemented.
