### ISSUE TITLE
Clarify the state of the project in the README

### ISSUE THREAD

**Issue by JordonPhillips** [google/grumpy#3]
Going through the README it seems like the project is in a more-or-less complete state. However, [this blog post](https://opensource.googleblog.com/2017/01/grumpy-go-running-python.html) indicates that isn't the case:

> There are still holes to fill — many built-in types are missing methods and attributes, built-in functions are absent and the standard library is virtually empty.

It would be good to clarify that in the README to avoid confusion.

**Comment by trotterdylan** [comment]
Fixed in https://github.com/google/grumpy/pull/51

Let me know if there are other details you'd like to see.
