### ISSUE TITLE
No support for requests, struct, cjson, boto and pika modules

### ISSUE THREAD

**Issue by ch3ck** [google/grumpy#301]
Grumpy currently lacks support for the following `python` modules:
* [ ] requests module
* [ ] struct module
* [ ] cjson module
* [ ] boto module
* [ ] pika module

**Comment by corona10** [comment]
@Ch3ck 
Those modules are not supported at current grumpy implementation's level.
To support such modules, features of CPython must be implemented first.
See this [docs](https://github.com/google/grumpy/wiki/Missing-features)
Related PR is always welcomed.

**Comment by Ch3ck** [comment]
@corona10  I see, that makes alot more sense now. I'll check out the documentation and see what I can do.
