### ISSUE TITLE
grumpy.compiler.util.ImportError: line 2: no such module: flask

### ISSUE THREAD

**Issue by thztech** [google/grumpy#315]
grumpy.compiler.util.ImportError: line 2: no such module: flask

**Comment by trotterdylan** [comment]
You're getting this error because you're trying to import flask but don't have any src/\_\_python\_\_/flask.py or src/\_\_python\_\_/flask/\_\_init\_\_.py in your GOPATH.

If you're trying to use the flask library you're going to be disappointed because it's not yet supported.
