### ISSUE TITLE
gox.

### ISSUE THREAD

**Issue by necrose99** [google/grumpy#349]
https://github.com/mitchellh/gox, run the build against gox. 

no docker no CHROOT for arches required. 

add gox support. 

Gox is a simple, no-frills tool for Go cross compilation that behaves a lot like standard go build. Gox will parallelize builds for multiple platforms. Gox will also build the cross-compilation toolchain for you.

**Comment by trotterdylan** [comment]
I don't see the benefit currently. Maybe once the build requirements are more clear.

**Comment by necrose99** [comment]
mainly gox will do windows 32/64 , LINUX 32/64 , BSD 32/64 , MACOS,etc....  
basicly if you need a go binary it will via gox you can build on a single machine but deploy many.. 

gox [hugo](https://github.com/gohugoio/hugo)  main.go ,  in theory you could rig the makefile , to use gox wrapper to goexe build....  , (ex.)   thus getting multiple executables , for multiple platforms.. 

grumpy -gox  my-py-script..py   my-new.go  -g-comp test.exe 
test.32.exe , test64.exe , test.32Linux.so , test.64-Linux-.so ,BSD, etc... 

mainly if compiling the go files...  just gives a lazy means of cross-compile in a hurry.  also allows deployment via muti-platform at scale...

**Comment by trotterdylan** [comment]
Thanks for the extra details. I do plan simplifications to the make system and more reliance on go build. If that doesn't suffice and cross compilation becomes an important use case then I may give Gox more consideration. 

My main hesitance is in adding more dependencies. Currently Grumpy depends on very little and I'll need a very good reason to add more.

**Comment by necrose99** [comment]
no biggy , I just figured as a user option  ie via config or file  -gox   sometime down the line...  as a optional feature.. most users won't need , but for devs/power "Ab-user-s"  a nice to have when called for. 
mainly it would make windows/ etc ports  less a pain...    some clients , "need a toy".. restrict python to even run the "toy"..  on jump boxes.. 
.  so thus getting a go-bin so cross building out a file as the occasional as needed one-off would be handy from time to time. 
I do SIEM deploys , so getting reports , on deploy , and diag some of the py scripts from windows jump boxes..... when python aint going to be installed........ nuts...
