### ISSUE TITLE
binary op not implemented: Pow

### ISSUE THREAD

**Issue by MirkoDziadzka** [google/grumpy#36]
# how to reproduce

try to compile

```
MAX_TCP_PORT = (2 ** 16) - 1
```

# expected result

it compiles

# actual result

```
line 3: binary op not implemented: Pow
```

**Comment by MirkoDziadzka** [comment]
https://github.com/MirkoDziadzka/grumpy/commit/9ad4a5ad148ca7b356750b15a114ba710d6739f8 solved my immediate problem. But the implementation is neither complete, nor necessary correct or tested

**Comment by dpavlin** [comment]
Thanks, I had same problem and your patched helped. Let's hope we will see it in upstream version soon.

**Comment by MirkoDziadzka** [comment]
Please note that this

- works only for integers, not long integers or floating point numbers
- works only if the result can be converted into a signed 64bit number (if the result is too big, you will get negative numbers, try 2 ** 64)
- may loose precision for large numbers

So it is by no means a fix for the problem, only a hot-fix for some cases which solved _my_ needs.

**Comment by trotterdylan** [comment]
@MirkoDziadzka Thanks for the PR. I commented on it. I'm fine with an incomplete implementation but I just want to make sure we fail hard when we encounter an overflow situation rather than silently giving bad results.
