### ISSUE TITLE
make returns <autogenerated>:1:0: cannot use _ as value

### ISSUE THREAD

**Issue by RezaGhanbari** [google/grumpy#385]
Go version: 
go1.9.2 darwin/amd64

Using latest grumpy version
`git clone git@github.com:google/grumpy.git`
`cd grumpy`
`make` 
it returns:
`<autogenerated>:1:0: cannot use _ as value make: *** [build/pkg/darwin_amd64/grumpy.a] Error 1`

what's wrong?

**Comment by hootoconnor** [comment]
Third party issue..https://github.com/google/grumpy/issues/35
