### ISSUE TITLE
expected 'IDENT', found 'INT' 7

### ISSUE THREAD

**Issue by owenkealey** [google/grumpy#391]
Hello,

Whenever I use this tool, it transpiles without error, but then when I try to run the Go file it produces, I am hit with this error

**Comment by owenkealey** [comment]
changing the package from 7 to main also doesnt help as that results in the following error:

runtime.main_main·f: relocation target main.main not defined
runtime.main_main·f: undefined: "main.main"

**Comment by alanjds** [comment]
Can you provide the program you are trying to transpile+compile+run ? Including the file name.
