### ISSUE TITLE
Dylan: Be a guest on Talk Python To Me about Grumpy?

### ISSUE THREAD

**Issue by mikeckennedy** [google/grumpy#55]
Hi Dylan,

You're a tough guy to find contact info for, so I'll file an issue for my request. :)

Would you be up for coming on https://talkpython.fm/ to talk about your project? I'd love to chat with you.

Best,
Michael

**Comment by trotterdylan** [comment]
:) You're persistent. I'll reply on LinkedIn. Just haven't gotten around to it yet.

**Comment by mikeckennedy** [comment]
Thanks Dylan. I appreciate it.
