### ISSUE TITLE
augmented assignment op not implemented: RShift

### ISSUE THREAD

**Issue by luckcolors** [google/grumpy#56]
I'm trying to compile this library [https://pypi.python.org/pypi/construct/](https://pypi.python.org/pypi/construct/), i didn't compile debug because it required pdb, if you think it's worth to implement, i'll make an issue for that stdlibrary.

This has happened on files:
```
core.py: line 22
lib/binary.py line 807
```

**Comment by trotterdylan** [comment]
Thanks for the report! A separate issue for pdb would be useful.

**Comment by luckcolors** [comment]
Ok will do. I'll make an issue wher ei put a list of modules wich are missing and need work and ones that just work as they are.

**Comment by luckcolors** [comment]
Any news on this?

**Comment by trotterdylan** [comment]
Just prepared a PR. Will merge shortly.
