### ISSUE TITLE
Stdlib list: Missing and Confirmed to be working as they are.

### ISSUE THREAD

**Issue by luckcolors** [google/grumpy#59]
## You can contribute to this on the wiki by using this link

https://github.com/google/grumpy/wiki/Missing-Features

**Comment by ns-cweber** [comment]
There's no way for others to edit your issue, so maybe this isn't the best way to track this? I'm thinking a md file or a section in the README might be better, but I don't know how much PR noise that would create for @trotterdylan. A Google doc might be a reasonable alternative, at least in the short term.

**Comment by trotterdylan** [comment]
I added a [wiki page](https://github.com/google/grumpy/wiki/Missing-Features) to track missing features. I think anybody can edit it. What do you guys think?

**Comment by ns-cweber** [comment]
I like the idea of having it on the wiki, but I think you're the only one with write permissions. I suspect we'd have to submit PRs to change it, which seems like it could generate a lot of noise.

**Comment by luckcolors** [comment]
This is a good idea to use the wiki! I'll change my comment.

**Comment by luckcolors** [comment]
Also should we for every .py file or lib include a link on the name?
Because not all of the libs are available in the Cpython Libs folder.
This fof example has appened for imp.py wich is imported by inspect.py but for some reason it's not present in my local cpython install but it is present in the original repo, or in case we decide to use one from somewhere else entirely.

**Comment by trotterdylan** [comment]
@ns-cweber It may be a bit noisy, but I'm willing to try it out. The reviews should be pretty low intensity. Feel free to request changes to the wiki.

@luckcolors Links make sense to me.

**Comment by trotterdylan** [comment]
I'm going to close this in favor of the [wiki page](https://github.com/google/grumpy/wiki/Missing-Features).
