### ISSUE TITLE
Support decorators PEP 318

### ISSUE THREAD

**Issue by trotterdylan** [google/grumpy#72]
https://www.python.org/dev/peps/pep-0318/

**Comment by trotterdylan** [comment]
Note that for starters it'd be nice if we would just fail hard when decorators are present in the ast.

**Comment by S-YOU** [comment]
@trotterdylan 
I am trying to implement to fail hard, but I am seeing alot of decorators already in the code

https://github.com/google/grumpy/blob/master/third_party/stdlib/_abcoll.py
third_party/stdlib/UserDict.py
third_party/stdlib/collections.py

**Comment by trotterdylan** [comment]
We can replace those with the verbose 'foo = decorator(foo)' for the time
being.

**Comment by S-YOU** [comment]
> We can replace those with the verbose 'foo = decorator(foo)' for the time
being.

Is that mean [classmethod](#73) has to be implemented first?

**Comment by trotterdylan** [comment]
Yeah I guess that is necessary first :\
