### ISSUE TITLE
Support classmethod

### ISSUE THREAD

**Issue by trotterdylan** [google/grumpy#73]
https://docs.python.org/2/library/functions.html#classmethod

**Comment by S-YOU** [comment]
I am wondering about `from_iterable = classmethod(from_iterable)` approach,
Isn't `classmethod` need to know which class it is in?

Usage in `chain.from_iterable` or `UserDict.fromkeys`, 
both try to instantiate class instance right inside those functions, 
which means you need to pass Class itself as first parameter.

**Comment by trotterdylan** [comment]
`classmethod` is a pretty straightforward application of the descriptor protocol. The class is passed as the last parameter of the `__get__` method:

```
>>> class Desc(object):
...   def __get__(self, obj, cls):
...     print cls
...
>>> class C(object):
...   foo = Desc()
...
>>> C.foo
<class '__main__.C'>
```

Here's CPython's implementation: https://github.com/python/cpython/blob/2.7/Objects/funcobject.c#L586
