### ISSUE TITLE
Missing support for string slicing

### ISSUE THREAD

**Issue by frankban** [google/grumpy#77]
This error is returned at runtime: `TypeError: string indices must be integers, not slice`.

**Comment by ns-cweber** [comment]
I reproduced with `print("hello"[1:-1])`.

**Comment by trotterdylan** [comment]
Thanks for reporting this. Proper slice support was never implemented for str and unicode, although it is implemented for tuples and lists [here](https://github.com/google/grumpy/blob/master/runtime/seq.go#L170). It should be a simple matter of handling slice type arguments for str [here](https://github.com/google/grumpy/blob/master/runtime/str.go#L204) and similarly for unicode.

**Comment by frankban** [comment]
Thanks for the quick fix!
