### ISSUE TITLE
how to import github Go packages

### ISSUE THREAD

**Issue by sebgoa** [google/grumpy#78]
we can import standard go packages, but how to add a package from a github reference ?
For example for `github.com/gorilla/mux`

I don't think the syntax is supported in `grumpc`

The following gets parsed but is wrong:

```
from __go__.net.http import ListenAndServe, RedirectHandler
from __go__.github.com.gorilla.mux import NewRouter
```

it leads to:

```
import (
        π_githubΓcomΓgorillaΓmux "github/com/gorilla/mux"
```

**Comment by trotterdylan** [comment]
Thanks for the report. This has also been noted in https://github.com/google/grumpy/issues/11. I'm interested in hearing opinions on how it should be supported if you wouldn't mind weighing in there.
