### ISSUE TITLE
how to run make

### ISSUE THREAD

**Issue by aihuasxy** [google/grumpy#89]
how to run 'make run' in Mac os?

My steps:
1. clone grumpy into local directory, for example ~/test
2. cd test
3. echo "print 'hello, world'" | make run

failed:
```
sxy@Mac ~/test/grumpy$ echo 'print "hello world"' | make run
build/src/grumpy/lib/errno/module.go:174: undefined: syscall.EADV
build/src/grumpy/lib/errno/module.go:190: undefined: syscall.EBADE
build/src/grumpy/lib/errno/module.go:198: undefined: syscall.EBADFD
build/src/grumpy/lib/errno/module.go:206: undefined: syscall.EBADR
build/src/grumpy/lib/errno/module.go:210: undefined: syscall.EBADRQC
build/src/grumpy/lib/errno/module.go:214: undefined: syscall.EBADSLT
build/src/grumpy/lib/errno/module.go:218: undefined: syscall.EBFONT
build/src/grumpy/lib/errno/module.go:234: undefined: syscall.ECHRNG
build/src/grumpy/lib/errno/module.go:238: undefined: syscall.ECOMM
build/src/grumpy/lib/errno/module.go:258: undefined: syscall.EDEADLOCK
build/src/grumpy/lib/errno/module.go:258: too many errors
make: *** [build/pkg/darwin_amd64/grumpy/lib/errno.a] Error 1
```

**Comment by S-YOU** [comment]
Oops, this could be result of my PR #85, will take a look

**Comment by kit1978** [comment]
ขอบคุณครับ⁣หมอ!

ส่งจาก BlueMail ​

ใน 11 ม.ค. 2017, 19:25 ที่ 19:25 YOU <notifications@github.com> เขียน:

**Comment by S-YOU** [comment]
@trotterdylan, currently we cannot do
```
import __go__.syscall
```
nor
``` 
__import__('__go__.syscall.EADV')
```
so, may be need to revert my commit #85 and hard-code them when needed.

**Comment by trotterdylan** [comment]
I think this should be fixed now. Please reopen if not.

**Comment by kit1978** [comment]
⁣ใช้ได้แล้วครับ ขอบคุณพี่มากๆ ครับ ที่มีน้ำใจกับผม พี่เก่งจริงๆ

ส่งจาก BlueMail ​

ใน 11 ม.ค. 2017, 21:56 ที่ 21:56 Dylan Trotter <notifications@github.com> เขียน:
