### ISSUE TITLE
cannot find package "grumpy/lib/argparse"

### ISSUE THREAD

**Issue by BrickXu** [google/grumpy#92]
Hi guys, 

I translate my python script to go with grumpy and it shows:
```
cannot find package "grumpy/lib/argparse"
```
And `argparse` did not list in the [Missing-Features](https://github.com/google/grumpy/wiki/Missing-Features#standard-libraries), how to resolve this problem ?

**Comment by S-YOU** [comment]
Actually, the whole standard library need to work on except a few.

https://github.com/google/grumpy/tree/master/third_party/stdlib
https://github.com/google/grumpy/tree/master/lib

Even those listed there, most of them are incomplete yet.

**Comment by trotterdylan** [comment]
Thanks for reporting this. I've added argparse to the [Missing Features page](https://github.com/google/grumpy/wiki/Missing-Features).

**Comment by BrickXu** [comment]
thanks @S-YOU  @trotterdylan
